server:
  port: 8080

spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host:
    port:
    username:
    password:
  flyway:
    enabled: true
jwt:
  secret: secret