server:
  port: ${PORT:8080}
  base_url: ${BASE_URL}
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
mailjet:
  mail:
    from: ${MAIlJET_MAIL_FROM}
    key: ${MAIlJET_MAIL_KEY}
    secret: ${MAIlJET_MAIL_SECRET}
    version: v3.1
    email_admin: ${MAIlJET_MAIL_EMAIL_ADMIN}
  flyway:
    enabled: true
jwt:
  secret: ${JWT_SECRET}
cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
html:
  file:
    register: ./src/main/resources/messages/register.html
    recovery: ./src/main/resources/messages/recovery.html