server:
  port: 8080

spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: jpro021social@gmail.com
    password: SocialNetwork021
  flyway:
    enabled: true
registration:
  verification:
    url: localhost:8080/api/v1/account/register/complete
jwt:
  secret: secret