server:
  port: 8080
  base_url: http://localhost:8080
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
mailjet:
  mail:
    from: admin@zeronenetwork.design
    key: 31630259aad78bb4a4adff1902eee4c3
    secret: cc6adb843048afd0f1a7d9c33feb4b22
    version: v3.1
  flyway:
    enabled: true
jwt:
  secret: secret
captcha:
  width: 193
  height: 57
  image: data:captchaImage/png;base64,
  lifespanBySec: 0
cloudinary:
  cloudName: dcn3kveee
  apiKey: 695884337247625
  apiSecret: U4D89gdUoSYLhK1eBCPCTOo1TvE