spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host:
    port:
    username:
    password:
  flyway:
    enabled: true

