server:
  port: ${PORT:8080}
  base_url: https://zerone2022-develop.herokuapp.com
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://ec2-3-228-75-39.compute-1.amazonaws.com:5432/dao27bpd0aa7h7
    username: ccrugjjcvoywty
    password: 98165e4c5b45cb8043084a53e5c90fb4ba518aada882cc3d679b414035e662b0
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
mailjet:
  mail:
    key: 31630259aad78bb4a4adff1902eee4c3
    from: admin@zeronenetwork.design
    secret: cc6adb843048afd0f1a7d9c33feb4b22
    version: v3.1
  flyway:
    enabled: true
jwt:
  secret: secret
captcha:
  width: 193
  height: 57
  image: data:captchaImage/png;base64,
  lifespanBySec: 0
cloudinary:
  cloudName: dcn3kveee
  apiKey: 695884337247625
  apiSecret: U4D89gdUoSYLhK1eBCPCTOo1TvE