spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  mail:
    host:
    port:
    username:
    password:
  flyway:
    enabled: true

