server:
  port: 8080
  base_url: ${BASE_URL}
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
mailjet:
  mail:
    key: ${MAIlJET_MAIL_KEY}
    from: ${MAIlJET_MAIL_FROM}
    secret: ${MAIlJET_MAIL_SECRET}
    version: v3.1
  flyway:
    enabled: true
jwt:
  secret: ${JWT_SECRET}
captcha:
  width: 193
  height: 57
  image: data:captchaImage/png;base64,
  lifespanBySec: 0