server:
  port: ${PORT:8080}
  base_url: ${BASE_URL}
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://ec2-3-228-75-39.compute-1.amazonaws.com:5432/dao27bpd0aa7h7
    username: ccrugjjcvoywty
    password: 98165e4c5b45cb8043084a53e5c90fb4ba518aada882cc3d679b414035e662b0    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
mailjet:
  mail:
    from: ${MAIlJET_MAIL_FROM}
    key: ${MAIlJET_MAIL_KEY}
    secret: ${MAIlJET_MAIL_SECRET}
    version: v3.1
    email_admin: briz.zukkel@gmail.com
  flyway:
    enabled: true
jwt:
  secret: ${JWT_SECRET}
captcha:
  width: 193
  height: 57
  image: data:captchaImage/png;base64,
  lifespanBySec: 0
cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
html:
  file:
    register: ./src/main/resources/messages/register.html
    recovery: ./src/main/resources/messages/recovery.html
