server:
  port: 8080
  base_url: http://localhost:8080

spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mail.ru
    port: 465
    username:  jpo021social@mail.ru
    password: SocialNetwork0211
  flyway:
    enabled: true
registration:
  verification:
    url: localhost:8080/api/v1/account/register/complete
recovery:
  pass:
    verification:
      url: localhost:8080/api/v1/account/password/recovery/complete
jwt:
  secret: secret