server:
  port: 8080
  base_url: http://localhost:8080
spring:
  messages:
    basename: lang.messages
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/SocialNetwork
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
mailjet:
  mail:
    key: 42ab394187a24011ecdcb095ff7fe4b6
    from: jpa021network@mail.ru
    secret: e70ed72dd4cfecf672bac3e516762acb!
    version: v3.1
  flyway:
    enabled: true
registration:
  verification:
    url: localhost:8080/api/v1/account/register/complete
recovery:
  pass:
    verification:
      url: localhost:8080/api/v1/account/password/recovery/complete
jwt:
  secret: secret